version: '3.6'

services:
    database:
        image: postgres:10
        container_name: database
        restart: always
        environment:
        - POSTGRES_PASSWORD=mobius
        - POSTGRES_USER=mobius
        - POSTGRES_DB=mobius
        ports:
        - 5432:${POSTGRES_PORT:-5432}
    mobius_server:
        container_name: mobius 
        hostname: mobius 
        image: rencinrig/mobius:latest
        restart: always
        depends_on:
        - database 
        environment:
        - MOBIUS_HOME=/code/
        ports:
        - "8080:8080"
        # point to user specific keys below
        volumes:
        - "./logs:/code/logs"
          #- "./mobius-sync:/code/mobius-sync"
        - "./config/application.properties:/code/config/application.properties"
        - "./config/log4j2.properties:/code/config/log4j2.properties"
        - "~/.ssh/geni-kthare10.pem:/code/ssh/geni-kthare10.pem"
        - "~/.ssh/id_rsa.pub:/code/ssh/id_rsa.pub"
        - "~/.ssh/id_rsa:/code/ssh/id_rsa"
        - "../mobius/src/main/resources/DigiCertCA.crt:/code/config/DigiCertCA.crt"
        - "../mobius/src/main/resources/client.jks:/code/config/client.jks"
