/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.renci.mobius.api;

import org.renci.mobius.model.MobiusResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-03-16T15:34:23.050-04:00[America/New_York]")
@Api(value = "listWorkflows", description = "the listWorkflows API")
public interface ListWorkflowsApi {

    @ApiOperation(value = "returs list of workflows", nickname = "listWorkflowsGet", notes = "Get the list of active workflows ", response = MobiusResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = MobiusResponse.class),
        @ApiResponse(code = 400, message = "Bad Request", response = MobiusResponse.class),
        @ApiResponse(code = 403, message = "Forbidden", response = MobiusResponse.class),
        @ApiResponse(code = 404, message = "Not Found", response = MobiusResponse.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = MobiusResponse.class),
        @ApiResponse(code = 200, message = "Unexpected Error", response = MobiusResponse.class) })
    @RequestMapping(value = "/listWorkflows",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<MobiusResponse> listWorkflowsGet();

}
