/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.renci.mobius.api;

import org.renci.mobius.model.MobiusResponse;
import org.renci.mobius.model.StitchRequest;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-04-10T13:40:16.803-04:00[America/New_York]")

@Api(value = "stitch", description = "the stitch API")
public interface StitchApi {

    @ApiOperation(value = "Request/modify stitching ", nickname = "stitchPost", notes = "Request/modify stitching ", response = MobiusResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = MobiusResponse.class),
        @ApiResponse(code = 400, message = "Bad Request", response = MobiusResponse.class),
        @ApiResponse(code = 403, message = "Forbidden", response = MobiusResponse.class),
        @ApiResponse(code = 404, message = "Not Found", response = MobiusResponse.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = MobiusResponse.class),
        @ApiResponse(code = 200, message = "Unexpected Error", response = MobiusResponse.class) })
    @RequestMapping(value = "/stitch",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<MobiusResponse> stitchPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody StitchRequest body,@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "workflowID", required = true) String workflowID);

}
